version: '3'

services:
    zookeeper:
      image: confluentinc/cp-zookeeper:5.4.0
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000

    kafka:
        image: confluentinc/cp-kafka:5.4.0
        depends_on:
          - zookeeper
        environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_NUM_PARTITIONS: 37
        ports:
          - "0.0.0.0:9092:9092"
          - "0.0.0.0:9093:9093"

    consul:
      image: consul:1.7
      ports:
        - "8500:8500"

    makinage-app:
        image: makinage-pypy:latest
        depends_on:
          - kafka
        environment:
          MAKINAGE_APP_COMMAND: ${MAKINAGE_APP_COMMAND}
        volumes:
          - ${MAKINAGE_APP_PATH}:/opt/makinage:ro
